version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      MONGODB_URI: mongodb://mongo:27017/symfony
      DATABASE_URL: mysql://root:@mysql:3306/arcadia_db
      MAILER_DSN=mailjet+api://06ffe4a76df69ee729705458a67250c2:54c397094fd53dbcd9fe0900e99f5a21@api:mailjet:com:

    depends_on:
      - mongo
      - mysql

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: arcadia_db

volumes:
  mongo_data:
  mysql_data:
