<?php

namespace ContainerFQiKvhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMongodb_Odm_Command_QueryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'doctrine_mongodb.odm.command.query' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Command\QueryDoctrineODMCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine_mongodb.odm.command.query'] = $instance = new \Doctrine\Bundle\MongoDBBundle\Command\QueryDoctrineODMCommand();

        $instance->setName('doctrine:mongodb:query');

        return $instance;
    }
}
