<?php

namespace ContainerFQiKvhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMongodb_Odm_Command_UpdateSchemaService extends App_KernelProdContainer
{
    /*
     * Gets the private 'doctrine_mongodb.odm.command.update_schema' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Command\UpdateSchemaDoctrineODMCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine_mongodb.odm.command.update_schema'] = $instance = new \Doctrine\Bundle\MongoDBBundle\Command\UpdateSchemaDoctrineODMCommand();

        $instance->setName('doctrine:mongodb:schema:update');

        return $instance;
    }
}
