<?php

namespace ContainerFQiKvhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMongodb_Odm_Command_GenerateHydratorsService extends App_KernelProdContainer
{
    /*
     * Gets the private 'doctrine_mongodb.odm.command.generate_hydrators' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Command\GenerateHydratorsDoctrineODMCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['doctrine_mongodb.odm.command.generate_hydrators'] = $instance = new \Doctrine\Bundle\MongoDBBundle\Command\GenerateHydratorsDoctrineODMCommand();

        $instance->setName('doctrine:mongodb:generate:hydrators');

        return $instance;
    }
}
