<?php

namespace ContainerFQiKvhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineMongodb_Odm_Command_LoadDataFixturesService extends App_KernelProdContainer
{
    /*
     * Gets the private 'doctrine_mongodb.odm.command.load_data_fixtures' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Command\LoadDataFixturesDoctrineODMCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Doctrine\Bundle\MongoDBBundle\Loader\SymfonyFixturesLoader();
        $a->addFixtures([]);

        $container->privates['doctrine_mongodb.odm.command.load_data_fixtures'] = $instance = new \Doctrine\Bundle\MongoDBBundle\Command\LoadDataFixturesDoctrineODMCommand(($container->services['doctrine_mongodb'] ?? self::getDoctrineMongodbService($container)), $a);

        $instance->setName('doctrine:mongodb:fixtures:load');

        return $instance;
    }
}
