<?php

namespace ContainerFQiKvhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitatTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\HabitatType' shared autowired service.
     *
     * @return \App\Form\HabitatType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\HabitatType'] = new \App\Form\HabitatType();
    }
}
