<?php

namespace ContainerFQiKvhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResetPasswordServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ResetPasswordService' shared autowired service.
     *
     * @return \App\Service\ResetPasswordService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\ResetPasswordService'])) {
            return $container->privates['App\\Service\\ResetPasswordService'];
        }

        return $container->privates['App\\Service\\ResetPasswordService'] = new \App\Service\ResetPasswordService('jurasikarcadia@gmail.com', ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->services['router'] ?? self::getRouterService($container)), $a);
    }
}
