<?php

namespace ContainerFQiKvhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeterinaryReportRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\VeterinaryReportRepository' shared autowired service.
     *
     * @return \App\Repository\VeterinaryReportRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\VeterinaryReportRepository'] = new \App\Repository\VeterinaryReportRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
