<?php

namespace ContainerFQiKvhx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVeterinaryReportTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\VeterinaryReportType' shared autowired service.
     *
     * @return \App\Form\VeterinaryReportType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\VeterinaryReportType'] = new \App\Form\VeterinaryReportType(($container->privates['App\\Repository\\VeterinaryReportRepository'] ?? $container->load('getVeterinaryReportRepositoryService')));
    }
}
