<?php

namespace ContainerTeZ3ase;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoXSSService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\NoXSS' shared autowired service.
     *
     * @return \App\Service\NoXSS
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'NoXSS.php';

        return $container->privates['App\\Service\\NoXSS'] = new \App\Service\NoXSS();
    }
}
