<?php

namespace ContainerBPgBt6y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimalControllerlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cd9erhq.App\Controller\AnimalController::list()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cd9erhq.App\\Controller\\AnimalController::list()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'animalRepository' => ['privates', 'App\\Repository\\AnimalRepository', 'getAnimalRepositoryService', true],
            'veterinaryReportRepository' => ['privates', 'App\\Repository\\VeterinaryReportRepository', 'getVeterinaryReportRepositoryService', true],
        ], [
            'animalRepository' => 'App\\Repository\\AnimalRepository',
            'veterinaryReportRepository' => 'App\\Repository\\VeterinaryReportRepository',
        ]))->withContext('App\\Controller\\AnimalController::list()', $container);
    }
}
