<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFQiKvhx\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFQiKvhx/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFQiKvhx.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFQiKvhx\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerFQiKvhx\App_KernelProdContainer([
    'container.build_hash' => 'FQiKvhx',
    'container.build_id' => '6918a324',
    'container.build_time' => 1721409509,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFQiKvhx');
