<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Animal extends \App\Entity\Animal implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'animalFeedings' => [parent::class, 'animalFeedings', null],
        "\0".parent::class."\0".'habitat' => [parent::class, 'habitat', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'race' => [parent::class, 'race', null],
        "\0".parent::class."\0".'veterinaryReports' => [parent::class, 'veterinaryReports', null],
        'animalFeedings' => [parent::class, 'animalFeedings', null],
        'habitat' => [parent::class, 'habitat', null],
        'id' => [parent::class, 'id', null],
        'image' => [parent::class, 'image', null],
        'name' => [parent::class, 'name', null],
        'race' => [parent::class, 'race', null],
        'veterinaryReports' => [parent::class, 'veterinaryReports', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
