<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2NxSQfJ\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2NxSQfJ/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container2NxSQfJ.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container2NxSQfJ\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container2NxSQfJ\App_KernelTestDebugContainer([
    'container.build_hash' => '2NxSQfJ',
    'container.build_id' => '912a613d',
    'container.build_time' => 1731865972,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container2NxSQfJ');
