<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTeZ3ase\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTeZ3ase/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerTeZ3ase.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerTeZ3ase\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerTeZ3ase\App_KernelTestDebugContainer([
    'container.build_hash' => 'TeZ3ase',
    'container.build_id' => 'e5ef784b',
    'container.build_time' => 1724261523,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTeZ3ase');
