<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerREFENJ0\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerREFENJ0/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerREFENJ0.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerREFENJ0\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerREFENJ0\App_KernelTestDebugContainer([
    'container.build_hash' => 'REFENJ0',
    'container.build_id' => 'b8fbdb01',
    'container.build_time' => 1732032836,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerREFENJ0');
