<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIj3WfFZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIj3WfFZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIj3WfFZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIj3WfFZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIj3WfFZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ij3WfFZ',
    'container.build_id' => '6add5108',
    'container.build_time' => 1724248920,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIj3WfFZ');
