<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJv0Nfom\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJv0Nfom/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJv0Nfom.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJv0Nfom\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJv0Nfom\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jv0Nfom',
    'container.build_id' => '2278f2d1',
    'container.build_time' => 1721567582,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJv0Nfom');
