<?php

namespace Container2NxSQfJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordResetControllerrequestService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.2efXEkM.App\Controller\PasswordResetController::request()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2efXEkM.App\\Controller\\PasswordResetController::request()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'resetPasswordService' => ['privates', 'App\\Service\\ResetPasswordService', 'getResetPasswordServiceService', true],
        ], [
            'entityManager' => '?',
            'resetPasswordService' => 'App\\Service\\ResetPasswordService',
        ]))->withContext('App\\Controller\\PasswordResetController::request()', $container);
    }
}
