<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Schedule extends \App\Entity\Schedule implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'closing_time' => [parent::class, 'closing_time', null],
        "\0".parent::class."\0".'day' => [parent::class, 'day', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isClosed' => [parent::class, 'isClosed', null],
        "\0".parent::class."\0".'opening_time' => [parent::class, 'opening_time', null],
        'closing_time' => [parent::class, 'closing_time', null],
        'day' => [parent::class, 'day', null],
        'id' => [parent::class, 'id', null],
        'isClosed' => [parent::class, 'isClosed', null],
        'opening_time' => [parent::class, 'opening_time', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
