<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VeterinaryReport extends \App\Entity\VeterinaryReport implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'animal' => [parent::class, 'animal', null],
        "\0".parent::class."\0".'detail' => [parent::class, 'detail', null],
        "\0".parent::class."\0".'food' => [parent::class, 'food', null],
        "\0".parent::class."\0".'food_weight' => [parent::class, 'food_weight', null],
        "\0".parent::class."\0".'health_status' => [parent::class, 'health_status', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'report_date' => [parent::class, 'report_date', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'animal' => [parent::class, 'animal', null],
        'detail' => [parent::class, 'detail', null],
        'food' => [parent::class, 'food', null],
        'food_weight' => [parent::class, 'food_weight', null],
        'health_status' => [parent::class, 'health_status', null],
        'id' => [parent::class, 'id', null],
        'report_date' => [parent::class, 'report_date', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
